site_name: Finetune
site_author: Finetune, Inc
site_description: The easiest way for developers to fine-tune AI agents.
theme:
  name: material
  custom_dir: overrides
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
    - header.autohide
  language: en
  palette:
    scheme: default
    primary: custom
    accent: custom

extra_css:
  - assets/custom.css

repo_url: https://github.com/yourusername/Finetune-Docs
repo_name: Finetune-Docs

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/yourusername/Finetune-Docs
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/yourusername

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

copyright: |
  &copy; 2024 <a href="https://github.com/yourusername/Finetune-Docs" target="_blank" rel="noopener">Finetune</a>

nav:
  - Home: index.md
  - Core Concepts:
    - Finetune Core Services: core-concepts/finetune-core-services.md
    - Fine-tuning Session:
      - Synthetic Users: core-concepts/fine-tuning-session/synthetic-users.md
      - Running agent against users: core-concepts/fine-tuning-session/running-agent-against-users.md
      - Added Weights: core-concepts/fine-tuning-session/added-weights.md
    - Feedback Session:
      - Finetune's Agent: core-concepts/feedback-session/finetunes-agent.md
      - Human Feedback: core-concepts/feedback-session/human-feedback.md
    - Weighted Execution Graph: core-concepts/weighted-execution-graph.md
    - Virtual Private Cloud Deployment: core-concepts/virtual-private-cloud-deployment.md
  - How-To Guides:
    - Integrate Your Agent: how-to/integrate-your-agent.md
    - Start a fine-tuning session:
      - Create, view & verify synthetic users: how-to/fine-tuning-session/create-view-verify-synthetic-users.md
      - View weights added: how-to/fine-tuning-session/view-weights-added.md
      - View fine-tuning report: how-to/fine-tuning-session/view-fine-tuning-report.md
    - Start a feedback session:
      - View Human Feedback: how-to/feedback-session/view-human-feedback.md
      - View feedback report: how-to/feedback-session/view-feedback-report.md
    - View WEG:
      - View updates to WEG: how-to/view-weg/view-updates-to-weg.md
    - Deploy your agent's WEG to a Virtual Private Cloud:
      - Reference WEG prior to every agent execution: how-to/deploy-weg-vpc/reference-weg-prior-to-execution.md
      - Perform CRUD operations: how-to/deploy-weg-vpc/perform-crud-operations.md
  - Examples:
    - Prepare for meetings: examples/prepare-for-meetings.md
    - Trip Planner Crew: examples/trip-planner-crew.md
    - Create Instagram Post: examples/create-instagram-post.md
    - Stock Analysis: examples/stock-analysis.md
    - Game Generator: examples/game-generator.md
    - Drafting emails with LangGraph: examples/drafting-emails-langgraph.md
    - Landing Page Generator: examples/landing-page-generator.md
  - FAQs:
    - Fine-tuning an agent? What's that?: faqs/what-is-fine-tuning-an-agent.md
    - Why fine-tune an agent?: faqs/why-fine-tune-an-agent.md
    - What is a weighted execution graph?: faqs/what-is-weighted-execution-graph.md
    - What is a Virtual Private Cloud?: faqs/what-is-a-vpc.md
    - Why does Finetune use a Virtual Private Cloud?: faqs/why-finetune-uses-it.md
    - How to connect my weighted execution graph to a Virtual Private Cloud?: faqs/how-to-connect-weg-to-vpc.md
    - Which cloud providers are integrated into Finetune?: faqs/which-cloud-providers-integrated.md
    - Which agents does Finetune support?: faqs/which-agents-finetune-supports.md
    - Which LLMs does Finetune support? Which are recommended?: faqs/which-llms-finetune-supports.md
    - How is the human feedback represented in the agent's WEG?: faqs/how-human-feedback-represented-in-weg.md